services:

  api:
    build: .
    container_name: fastapi-app
    restart: always
    ports:
      - "8000:8000"

  nginx:
    image: nginx
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

  netdata:
    image: netdata/netdata
    container_name: netdata
    restart: always
    ports:
      - "19999:19999"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor=unconfined
